name: Deploy MKDocs to GitHub Pages
on:
  release:
    types:
      - published
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
# Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          submodules: True

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      #  Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest pytest-cov coverage flake8 black mypy isort pylint
      
      - name: Install docs dependencies
        run: |
          pip install black mkdocs mkdocstrings mkdocstrings-python mkdocs-autorefs mkdocs-get-deps mkdocs-material>9.5.0
          pip install mkdocs-material-extensions markdown pymdown-extensions Pygments

      #  Install dependencies
      - name: Install dependencies
        run: |
          pip install cython>=3.0.2
          pip install pybind11
          

      #  Build the package
      - name: Build the package
        run: |
          python -m build

      # Install locally
      - name: Install the package
        run: |
          pip install -e . 

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            mkdocs-material-
          path: ~/.cache/pip

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure token has permissions to push to gh-pages
