name: Build,Lint and Publish to TestPyPI

on:
  release:
    types: [published]

jobs:
  build-test-lint-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest pytest-cov coverage

      # Step 4: Install lint and dependencies
      - name: Install lint dependencies
        run: |
          pip install cython>=3.0.2
          pip install pybind11
          pip install flake8

      # Step 5: Run linting
      - name: Run linting
        run: |
          flake8 charloratools/

      # Step 6: Build the package
      - name: Build the package
        run: |
          python -m build

      # Step 7: Publish to TestPyPI if all previous steps succeed
      - name: Publish to TestPyPI
        if: success()
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
